import 'records/domain/entities/resource_spec.dart';

/// true  = sign in with the Elyvori API and show the live agents dashboard.
/// false = a standalone offline-first app that opens straight on its modules.
const bool useElyvoriAgents = false;

/// The modules of this app, generated by Elyvori from the client's request.
const List<ResourceSpec> appResources = <ResourceSpec>[
  ResourceSpec(
    key: 'menu_items',
    title: 'المنيو',
    icon: 'menu',
    description: 'إدارة أطباق وأصناف الطعام في المطعم',
    fields: [
      FieldSpec(key: 'item_name', label: 'اسم الطبق', type: FieldType.text, required: true),
      FieldSpec(key: 'category', label: 'التصنيف', type: FieldType.text, required: true),
      FieldSpec(key: 'price', label: 'السعر', type: FieldType.number, required: true),
      FieldSpec(key: 'description', label: 'الوصف', type: FieldType.longText, required: false),
      FieldSpec(key: 'is_available', label: 'متوفر حالياً', type: FieldType.boolean, required: true),
    ],
  ),
  ResourceSpec(
    key: 'orders',
    title: 'الطلبات',
    icon: 'orders',
    description: 'متابعة طلبات الزبائن وحالتها',
    fields: [
      FieldSpec(key: 'order_number', label: 'رقم الطلب', type: FieldType.text, required: true),
      FieldSpec(key: 'customer_name', label: 'اسم الزبون', type: FieldType.text, required: true),
      FieldSpec(key: 'total_amount', label: 'المبلغ الإجمالي', type: FieldType.number, required: true),
      FieldSpec(key: 'order_status', label: 'حالة الطلب', type: FieldType.text, required: true),
      FieldSpec(key: 'order_date', label: 'وقت الطلب', type: FieldType.date, required: true),
    ],
  ),
  ResourceSpec(
    key: 'customers',
    title: 'الزبائن',
    icon: 'customers',
    description: 'قاعدة بيانات العملاء ومعلومات الاتصال',
    fields: [
      FieldSpec(key: 'customer_name', label: 'اسم الزبون', type: FieldType.text, required: true),
      FieldSpec(key: 'phone_number', label: 'رقم الهاتف', type: FieldType.phone, required: true),
      FieldSpec(key: 'delivery_address', label: 'عنوان التوصيل', type: FieldType.longText, required: false),
      FieldSpec(key: 'email', label: 'البريد الإلكتروني', type: FieldType.email, required: false),
    ],
  ),
];
